Bump rustc to `stable` for Kotlin CI
Due to:
```
error: package `clap v4.5.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.73.0
```