server: do not panic on --help command
This commit is including a simple check and suggest a help string
for the user when the command `--help` is used. Without this diff
applied the server will panic and the user will not have any clue
why.

     Running `target/debug/ldk-server --help`
thread 'main' panicked at ldk-server/src/main.rs:30:56:
Invalid configuration file.: Custom { kind: NotFound, error: "Failed to read config file '--help': No such file or directory (os error 2)" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    750067 IOT instruction (core dumped)  cargo run --bin ldk-server -- --help

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>